"""
Score the model against the gut-check pairs in gut_checks.csv and list
the top matches for the roster, so the formulas can be judged by eye.

The pairs were written down before the formulas existed. Add new pairs
to the CSV with the date; don't edit old ones after seeing results.

Output: validation_report.md
"""
import json
import unicodedata
from pathlib import Path

import numpy as np
import pandas as pd

from formulas import ATTRIBUTES, PROFILE_LEVEL_WEIGHT, TRAITS
from match import ranked_on, ranked_profile


ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT.parent / "data"
REPORT = ROOT / "validation_report.md"

TOP_N = 5


def plain(text):
    """Lowercase without accents, so 'Jokic' finds 'Jokić'."""
    return unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode().lower()


def load(name, key):
    """Records, their attribute vectors, and their levels."""
    records = json.loads((DATA_DIR / name).read_text(encoding="utf-8"))[key]
    vectors = np.array([[r["attributes"][a] for a in ATTRIBUTES] for r in records])
    levels = np.array([r["level"] for r in records])
    return records, vectors, levels


def profile_order(i, vectors, levels, candidates, candidate_levels):
    """Candidates ranked by whole-profile match to record i."""
    return ranked_profile(vectors[i], levels[i], candidates, candidate_levels,
                          PROFILE_LEVEL_WEIGHT)


def find(records, value):
    matches = [i for i, r in enumerate(records) if value in (plain(r["name"]), r.get("slug"))]
    return matches[0] if matches else None


def position(target, order):
    """1-based position of `target` in a ranked list of indices."""
    return int(np.where(order == target)[0][0]) + 1


def trait_columns(group):
    return [ATTRIBUTES.index(a) for a in group]


def names(order, records):
    return ", ".join(records[i]["name"] for i in order[:TOP_N])


def main():
    pokemon, poke_vectors, poke_levels = load("pokemon.json", "pokemon")
    players, nba_vectors, nba_levels = load("nba_players.json", "players")
    checks = pd.read_csv(ROOT / "gut_checks.csv")

    # Pokemon -> NBA matches only come from the match pool (2K overall 78+).
    pool = [i for i, r in enumerate(players) if r["match_pool"]]
    pool_players = [players[i] for i in pool]
    pool_vectors, pool_levels = nba_vectors[pool], nba_levels[pool]

    trait_headers = " | ".join(TRAITS)
    lines = [
        "# Validation report",
        "",
        f"Generated by validate.py. {len(pokemon)} Pokemon, {len(players)} NBA players.",
        "",
        "## Gut-check pairs",
        "",
        f"Where the Pokemon ranks among the player's matches (out of {len(pokemon)}), "
        "for the whole profile and for each trait. The last column is the "
        f"reverse: where the player ranks among the Pokemon's matches (out of "
        f"the {len(pool)} players rated 78+ in 2K). 1 = best match.",
        "",
        f"| NBA player | Pokemon | Confidence | whole profile | {trait_headers} | player rank |",
        "|---|---|---|---|" + "---|" * len(TRAITS) + "---|",
    ]

    for check in checks.itertuples():
        p = find(players, plain(check.nba_player))
        k = find(pokemon, check.pokemon)

        if p is None:
            lines.append(f"| {check.nba_player} | {check.pokemon} | {check.confidence} "
                         f"| not in the NBA data |" + " |" * (len(TRAITS) + 1))
            continue

        whole = position(k, profile_order(p, nba_vectors, nba_levels, poke_vectors, poke_levels))
        traits = [
            position(k, ranked_on(nba_vectors[p], poke_vectors, trait_columns(group)))
            for group in TRAITS.values()
        ]
        reverse = (
            position(pool.index(p), profile_order(k, poke_vectors, poke_levels,
                                                  pool_vectors, pool_levels))
            if p in pool else "not in match pool"
        )

        lines.append(
            f"| {players[p]['name']} | {pokemon[k]['name']} | {check.confidence} "
            f"| {whole} | " + " | ".join(map(str, traits)) + f" | {reverse} |"
        )

    def match_lines(i, vectors, levels, candidates, candidate_levels, records):
        order = profile_order(i, vectors, levels, candidates, candidate_levels)
        out = [f"- whole profile: {names(order, records)}"]
        for phrase, group in TRAITS.items():
            order = ranked_on(vectors[i], candidates, trait_columns(group))
            out.append(f"- {phrase}: {names(order, records)}")
        return out

    lines += ["", "## Gut-check players: top Pokemon", ""]
    for name in checks["nba_player"].unique():
        p = find(players, plain(name))
        if p is None:
            continue
        lines.append(f"**{players[p]['name']}**")
        lines += match_lines(p, nba_vectors, nba_levels, poke_vectors, poke_levels, pokemon)
        lines.append("")

    lines += ["## Roster: top NBA matches", ""]
    roster = [i for i, r in enumerate(pokemon) if r["roster"]]
    for k in sorted(roster, key=lambda i: (pokemon[i]["roster"], pokemon[i]["bst"])):
        lines.append(f"**{pokemon[k]['name']}** ({pokemon[k]['roster'].title()}, BST {pokemon[k]['bst']})")
        lines += match_lines(k, poke_vectors, poke_levels, pool_vectors, pool_levels, pool_players)
        lines.append("")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
